{{- $role := include "machineset.clusterRole" . -}}
{{- if ne $role "worker" -}}
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: {{ include "machineset.name" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    helm.sh/hook-weight: "0"
spec:
  machineConfigSelector:
    matchExpressions:
    - key: machineconfiguration.openshift.io/role
      operator: In
      values:
      - worker
      - {{ $role }}
{{- if $.Values.machineset.labels }}
  nodeSelector:
    matchLabels:
{{- toYaml (default $.Values.machineset.labels) | nindent 6 -}}
{{- end -}}
{{- end -}}