infrastructureId: ""

cloud:
  name: "" # aws, azure, ibmcloud or vsphere
  managed: false # for roks, aro, rosa set to true
  region: 
  zones: {}
  aws:
    ami:
  azure:
    resourceGroup:
    networkResourceGroup:
    virtualNetwork:
    workerSubnet:
  vsphere:
    networkName: 
    datacenter: 
    datastore: 
    cluster: 
    server:

machineset:
  name:
  clusterRole:
  clusterType:
  nodesPerZone: {}
  memoryMiB:
  numCPUs:
  numCoresPerSocket:
  volumeSize:
  volumeType:
  instanceType:
  taints: {}
  labels: {}



global:
  infraNodes:
    taints:
      - effect: "NoSchedule"
        key: "infra"
        value: ""
    labels:
      node-role.kubernetes.io/infra: ""
  storageNodes:
    taints:
      - effect: "NoSchedule"
        key: "node.ocs.openshift.io/storage"
        value: "true"
    labels:
      node-role.kubernetes.io/storage: ""
      cluster.ocs.openshift.io/openshift-storage: ""
  cloudpakNodes:
    taints:
    labels:
      node-role.kubernetes.io/cp4x: ""
