apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ibm-guardium-restricted-scc
rules:
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - restricted
    resources:
      - securitycontextconstraints
    verbs:
      - use